# Generated by Django 6.0 on 2026-05-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('classes', '0004_group_group_status_open_idx_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language_code',
            field=models.CharField(choices=[('uk', 'Ukrainian'), ('en', 'English')], default='uk', max_length=10),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['email'], name='email_verify_email_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['created_at'], name='email_verify_created_idx'),
        ),
        migrations.AddIndex(
            model_name='resetcode',
            index=models.Index(fields=['expire_at'], name='reset_code_expire_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['full_name'], name='user_full_name_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(('onboarding_status', 'new')), fields=['onboarding_status'], name='user_onboarding_new_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(('is_google_calendar_connected', True)), fields=['is_google_calendar_connected'], name='user_google_cal_connected_idx'),
        ),
    ]
