# Generated by Django 6.0 on 2026-04-16 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('recruiting', 'Recruiting'), ('active', 'Active'), ('finished', 'Finished'), ('archived', 'Archived')], default='active', max_length=20)),
                ('age_group', models.CharField(choices=[('kids', 'Kids'), ('teens', 'Teens'), ('adults', 'Adults')], max_length=20)),
                ('knowledge_level', models.CharField(choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('pre_intermediate', 'Pre-Intermediate'), ('intermediate', 'Intermediate'), ('upper_intermediate', 'Upper-Intermediate'), ('advanced', 'Advanced')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_online', models.BooleanField()),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('expelled', 'Expelled'), ('completed', 'Completed')], default='active', max_length=20)),
            ],
            options={
                'db_table': 'group_students',
            },
        ),
        migrations.CreateModel(
            name='InternalMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('training', 'Teacher Training'), ('staff_meeting', 'Staff Meeting'), ('one_on_one', '1-to-1 Sync')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('meet_link', models.URLField(blank=True, null=True)),
                ('html_link', models.URLField(blank=True, null=True)),
                ('color_id', models.CharField(choices=[('1', '#7986cb'), ('2', '#33b679'), ('3', '#8e24aa'), ('4', '#e67c73'), ('5', '#f6bf26'), ('6', '#f4511e'), ('7', '#039be5'), ('8', '#616161'), ('9', '#3f51b5'), ('10', '#0b8043'), ('11', '#d50000')], default='3', help_text='ID кольору в Google Calendar', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('actual_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('cancelled_reason', models.CharField(blank=True, max_length=255)),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('meet_link', models.URLField(blank=True, null=True)),
                ('html_link', models.URLField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('lesson_plan', models.TextField(blank=True, default='')),
                ('plan_status', models.CharField(choices=[('empty', 'Not Created'), ('draft', 'Draft'), ('on_review', 'On Review'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved')], default='empty', max_length=20)),
                ('plan_feedback', models.TextField(blank=True, null=True)),
                ('plan_approved_at', models.DateTimeField(blank=True, null=True)),
                ('lesson_number_in_course', models.IntegerField(blank=True, null=True)),
                ('color_id', models.CharField(choices=[('1', '#7986cb'), ('2', '#33b679'), ('3', '#8e24aa'), ('4', '#e67c73'), ('5', '#f6bf26'), ('6', '#f4511e'), ('7', '#039be5'), ('8', '#616161'), ('9', '#3f51b5'), ('10', '#0b8043'), ('11', '#d50000')], default='3', help_text='ID кольору в Google Calendar', max_length=2)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled_by_teacher', 'Cancelled by Teacher'), ('cancelled_by_student', 'Cancelled by Student'), ('cancelled_by_system', 'Cancelled by System'), ('rescheduled', 'Rescheduled'), ('no_show_teacher', 'No Show (Teacher)'), ('no_show_group', 'No Show (Group)')], default='scheduled', max_length=30)),
            ],
            options={
                'db_table': 'lessons',
            },
        ),
        migrations.CreateModel(
            name='LessonStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Тривалість у хвилинах')),
            ],
            options={
                'db_table': 'lesson_types',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
            ],
            options={
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='SchoolAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'school_affiliations',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='todo', max_length=15)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('google_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_tasklist_id', models.CharField(default='@default', max_length=255)),
            ],
            options={
                'db_table': 'task',
                'ordering': ['-created_at'],
            },
        ),
    ]
