# Generated by Django 6.0 on 2026-05-01 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_initial'),
        ('courses', '0003_course_course_active_idx_course_course_level_idx_and_more'),
        ('gradebook', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='group',
            index=models.Index(condition=models.Q(('status__in', ['finished', 'archived']), _negated=True), fields=['status'], name='group_status_open_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['school', 'status'], name='group_school_status_idx'),
        ),
        migrations.AddIndex(
            model_name='groupstudent',
            index=models.Index(condition=models.Q(('status__in', ['active', 'paused'])), fields=['status'], name='group_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='internalmeeting',
            index=models.Index(fields=['start_time'], name='meeting_start_time_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['start_time'], name='lesson_start_time_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['group', 'start_time'], name='lesson_group_start_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['teacher', 'start_time'], name='lesson_teacher_start_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['plan_status'], name='lesson_plan_status_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['city'], name='school_city_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-created_at'], name='task_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'status'], name='task_assignee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deadline'], name='task_deadline_idx'),
        ),
    ]
