# Generated by Django 6.0 on 2026-05-01 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_group_group_status_open_idx_and_more'),
        ('gradebook', '0003_attendance_attendance_category_idx_and_more'),
        ('homework', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['deadline'], name='homework_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['homework', 'student'], name='hw_submission_lookup_idx'),
        ),
    ]
