# Generated by Django 6.0 on 2026-04-16 13:44

import apps.testing.models.helpers.test_attempt
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingStudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_awarded', models.FloatField(default=0.0)),
                ('teacher_comment', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'onboarding_student_answers',
            },
        ),
        migrations.CreateModel(
            name='OnboardingTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('timed_out', 'Timed Out'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('max_possible_score', models.FloatField(default=0.0)),
                ('is_passed', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0)),
                ('anonymous_token', models.UUIDField(db_index=True, unique=True)),
            ],
            options={
                'db_table': 'onboarding_test_attempt',
                'ordering': ['-started_at'],
            },
            bases=(apps.testing.models.helpers.test_attempt.TestAttemptProps, models.Model),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text="Для Fill-in-blank питань юзаєм плейсхолдери, наприклад: 'London is the capital of {1}'")),
                ('text_uk', models.TextField(help_text="Для Fill-in-blank питань юзаєм плейсхолдери, наприклад: 'London is the capital of {1}'", null=True)),
                ('text_en', models.TextField(help_text="Для Fill-in-blank питань юзаєм плейсхолдери, наприклад: 'London is the capital of {1}'", null=True)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('points', models.FloatField(default=1)),
                ('type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('open_text', 'Open Text'), ('fill_in_the_blank', 'Fill in the blank'), ('matching', 'Matching'), ('ordering', 'Ordering')], max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField()),
                ('option_text_uk', models.TextField(null=True)),
                ('option_text_en', models.TextField(null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True)),
                ('correct_order', models.PositiveIntegerField(blank=True, help_text='For Ordering questions: the correct position (1, 2, 3)', null=True)),
                ('match_pair_text', models.CharField(blank=True, help_text='For Matching questions: the right side of the pair', max_length=500, null=True)),
                ('blank_group_id', models.PositiveIntegerField(blank=True, help_text='For Fill-in-the-blank: ID of the gap (1, 2...)', null=True)),
            ],
            options={
                'db_table': 'question_options',
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_awarded', models.FloatField(default=0.0)),
                ('teacher_comment', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'student_answers',
            },
        ),
        migrations.CreateModel(
            name='StudentAnswerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_response', models.TextField(blank=True)),
                ('placeholder_index', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student_answer_items',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uk', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_uk', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tests',
            },
        ),
        migrations.CreateModel(
            name='TestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('custom_time_limit', models.IntegerField(blank=True, help_text='Override original test time limit (minutes)', null=True)),
                ('custom_passing_score', models.IntegerField(blank=True, help_text='Override passing score (%)', null=True)),
                ('show_answers', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('starting_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closing_at', models.DateTimeField(blank=True, help_text='Override original test closing time', null=True)),
            ],
            options={
                'verbose_name': 'Test Assignment',
                'verbose_name_plural': 'Test Assignments',
                'db_table': 'test_assignments',
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('timed_out', 'Timed Out'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('max_possible_score', models.FloatField(default=0.0)),
                ('is_passed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'test_attempts',
                'ordering': ['-started_at'],
            },
            bases=(apps.testing.models.helpers.test_attempt.TestAttemptProps, models.Model),
        ),
        migrations.CreateModel(
            name='TestVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('time_limit_minutes', models.IntegerField(null=True)),
                ('passing_score_percent', models.IntegerField(default=60)),
                ('is_random_order', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'test_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingStudentAnswerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_response', models.TextField(blank=True)),
                ('placeholder_index', models.IntegerField(blank=True, null=True)),
                ('student_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='testing.onboardingstudentanswer')),
            ],
            options={
                'db_table': 'onboarding_student_answer_items',
            },
        ),
    ]
