# Generated by Django 6.0 on 2026-04-16 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0003_initial'),
        ('courses', '0002_initial'),
        ('gradebook', '0001_initial'),
        ('testing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingtestattempt',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onboardingstudentanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testing.onboardingtestattempt'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_question_options', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onboardingstudentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.question'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='testing.question'),
        ),
        migrations.AddField(
            model_name='onboardingstudentansweritem',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.questionoption'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.question'),
        ),
        migrations.AddField(
            model_name='studentansweritem',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.questionoption'),
        ),
        migrations.AddField(
            model_name='studentansweritem',
            name='student_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='testing.studentanswer'),
        ),
        migrations.AddField(
            model_name='test',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='grade_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_assignment', to='gradebook.gradecolumn'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_assignments', to='classes.group'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_assignments', to='classes.lesson'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_assignments', to='courses.material'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.test'),
        ),
        migrations.AddField(
            model_name='onboardingtestattempt',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.testassignment'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.testassignment'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gradebook.grade'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testing.testattempt'),
        ),
        migrations.AddField(
            model_name='testversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testversion',
            name='questions',
            field=models.ManyToManyField(related_name='test_versions', to='testing.question'),
        ),
        migrations.AddField(
            model_name='testversion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='testing.test'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='test_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='testing.testversion'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='pinned_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='testing.testversion'),
        ),
        migrations.AddField(
            model_name='test',
            name='current_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_test', to='testing.testversion'),
        ),
        migrations.AddField(
            model_name='onboardingtestattempt',
            name='test_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='testing.testversion'),
        ),
        migrations.AlterUniqueTogether(
            name='onboardingstudentanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='testversion',
            unique_together={('test', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='onboardingtestattempt',
            unique_together={('email', 'assignment'), ('student', 'assignment')},
        ),
    ]
