# Generated by Django 6.0 on 2026-05-01 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_group_group_status_open_idx_and_more'),
        ('courses', '0003_course_course_active_idx_course_course_level_idx_and_more'),
        ('gradebook', '0003_attendance_attendance_category_idx_and_more'),
        ('testing', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='onboardingtestattempt',
            index=models.Index(fields=['-started_at'], name='onboard_attempt_started_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingtestattempt',
            index=models.Index(condition=models.Q(('status', 'in_progress')), fields=['status'], name='onboard_attempt_progress_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['type'], name='question_type_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-created_at'], name='question_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='testassignment',
            index=models.Index(fields=['starting_at'], name='assignment_starting_idx'),
        ),
        migrations.AddIndex(
            model_name='testassignment',
            index=models.Index(fields=['closing_at'], name='assignment_closing_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['-started_at'], name='test_attempt_started_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(condition=models.Q(('status', 'in_progress')), fields=['status'], name='test_attempt_progress_idx'),
        ),
        migrations.AddIndex(
            model_name='testversion',
            index=models.Index(fields=['status'], name='test_version_status_idx'),
        ),
    ]
