# Generated by Django 6.0 on 2026-04-16 13:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('COMPLAINT', 'Complaint'), ('FEEDBACK', 'Feedback'), ('WISH', 'Wish')], default='FEEDBACK', max_length=15)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feedbacks',
            },
        ),
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_country_code', models.CharField(max_length=5)),
                ('phone_national_number', models.CharField(max_length=20)),
                ('phone_normalized', models.CharField(max_length=25)),
                ('message', models.TextField(blank=True)),
                ('contact_preference', models.CharField(choices=[('phone', 'Phone Call'), ('email', 'Email'), ('other', 'Other')], default='phone', max_length=20)),
                ('other_contact_preference', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('converted', 'Converted to Lead'), ('rejected', 'Rejected / Spam'), ('archived', 'Archived')], default='new', max_length=20)),
                ('callback_page', models.URLField(max_length=512)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_comment', models.TextField(blank=True)),
                ('converted_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_request', to='crm.lead')),
            ],
            options={
                'db_table': 'callback_request',
            },
        ),
    ]
