# Generated by Django 6.0 on 2026-04-16 13:44

import apps.core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', max_length=20)),
                ('late_minutes', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('classwork', 'Classwork'), ('homework', 'Homework'), ('test', 'Test'), ('speaking', 'Speaking'), ('project', 'Project'), ('task', 'Task')], max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('value', models.FloatField(default=0.0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='GradeColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'grade_columns',
            },
        ),
        migrations.CreateModel(
            name='GradeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.core.models.upload_to_document)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'grade_files',
            },
        ),
    ]
