# Generated by Django 6.0 on 2026-05-01 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_group_group_status_open_idx_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('gradebook', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['category'], name='attendance_category_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['content_type', 'object_id'], name='grade_content_obj_idx'),
        ),
        migrations.AddIndex(
            model_name='gradecolumn',
            index=models.Index(fields=['-date'], name='grade_col_date_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='gradecolumn',
            index=models.Index(fields=['group', '-date'], name='grade_col_group_date_idx'),
        ),
    ]
