# Generated by Django 6.0 on 2026-05-01 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['is_active'], name='course_active_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['level'], name='course_level_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemodule',
            index=models.Index(fields=['course', 'sort_order'], name='module_course_order_idx'),
        ),
        migrations.AddIndex(
            model_name='coursetopic',
            index=models.Index(fields=['module', 'sort_order'], name='topic_module_order_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['access_level'], name='material_access_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deadline'], name='course_task_deadline_idx'),
        ),
    ]
