# Generated by Django 6.0 on 2026-04-16 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pnl_category',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='USD, UAH, ...', max_length=15, unique=True)),
                ('name', models.CharField(help_text='Долар, ще якась канєтєль', max_length=50)),
                ('symbol', models.CharField(help_text='$, 卍, ...', max_length=10)),
            ],
            options={
                'db_table': 'pnl_currency',
            },
        ),
        migrations.CreateModel(
            name='GiftCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сума, яку реально заплатили', max_digits=10)),
                ('purchaser_name', models.CharField(max_length=255)),
                ('purchaser_email', models.EmailField(max_length=254)),
                ('issued_to_email', models.EmailField(help_text='Email друга, якому прийде подарунок', max_length=254)),
                ('issued_to_name', models.CharField(blank=True, help_text="Ім'я друга для красивого листа", max_length=255)),
                ('is_paid', models.BooleanField(default=False, help_text='Стає True після успішної оплати у WayForPay')),
                ('is_used', models.BooleanField(default=False)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gift_certificates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_reference', models.CharField(max_length=255, unique=True)),
                ('payment_type', models.CharField(choices=[('new_sub', 'New Subscription'), ('top_up', 'Top Up Extra Lessons'), ('gift', 'Gift Certificate')], default='new_sub', max_length=20)),
                ('extra_lessons', models.IntegerField(blank=True, null=True)),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('refunded', 'Refunded'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('response_code', models.CharField(blank=True, max_length=50, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pnl_payment_method',
            },
        ),
        migrations.CreateModel(
            name='SchoolBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'pnl_school_balance',
            },
        ),
        migrations.CreateModel(
            name='StudentSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending_assignment', 'Waiting for assignment'), ('active', 'Active'), ('frozen', 'Frozen'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_assignment', max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('lessons_remaining', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student_subscription',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pnl_subcategory',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="'The History of Germany', 'Aryans Today'", max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('lessons_count', models.PositiveIntegerField()),
                ('duration_days', models.PositiveIntegerField()),
                ('grace_period_days', models.PositiveIntegerField(default=0, help_text='Debt term in days(How many days student can attend lessons after end of sub term)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_lesson', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is available for users')),
            ],
            options={
                'db_table': 'subscription_plan',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='income', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pnl_transaction',
            },
        ),
        migrations.CreateModel(
            name='CompanyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='company_balance', to='finance.currency')),
            ],
            options={
                'db_table': 'pnl_company_balance',
            },
        ),
    ]
