# Generated by Django 6.0 on 2026-04-16 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0003_initial'),
        ('courses', '0002_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcertificate',
            name='purchaser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_gifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='redeemed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_gifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='target_gift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.giftcertificate'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolbalance',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency'),
        ),
        migrations.AddField(
            model_name='schoolbalance',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='classes.school'),
        ),
        migrations.AddField(
            model_name='studentsubscription',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='classes.group'),
        ),
        migrations.AddField(
            model_name='studentsubscription',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='target_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_up_payments', to='finance.studentsubscription'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='finance.category'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_plans', to='courses.course'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_plans', to='finance.currency'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='lesson_type',
            field=models.ForeignKey(blank=True, help_text="'Stay after classes Lesson', 'Individual'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.lessontype'),
        ),
        migrations.AddField(
            model_name='studentsubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sold_subscriptions', to='finance.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_certificates', to='finance.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.category'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.currency'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.paymentmethod'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='classes.school'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.subcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolbalance',
            unique_together={('school', 'currency')},
        ),
    ]
