# Generated by Django 6.0 on 2026-05-01 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_group_group_status_open_idx_and_more'),
        ('courses', '0003_course_course_active_idx_course_course_level_idx_and_more'),
        ('finance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='giftcertificate',
            index=models.Index(fields=['issued_to_email'], name='gift_issued_email_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-created_at'], name='payment_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsubscription',
            index=models.Index(fields=['-start_date'], name='sub_start_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsubscription',
            index=models.Index(fields=['status'], name='sub_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsubscription',
            index=models.Index(fields=['student', 'status'], name='sub_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['is_active'], name='plan_active_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-created_at'], name='txn_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['school', '-created_at'], name='txn_school_created_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type'], name='txn_type_idx'),
        ),
    ]
