# Generated by Django 6.0 on 2026-04-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('source', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('converted', 'Converted'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'leads',
            },
        ),
    ]
