# Generated by Django 6.0 on 2026-05-01 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(condition=models.Q(('status__in', ['new', 'processing'])), fields=['status'], name='lead_status_open_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['manager', 'status'], name='lead_manager_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email'], name='lead_email_idx'),
        ),
    ]
